dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.2
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}